import type { Macros } from "./foods";

export type Recipe = {
  id: string;
  nameRo: string;
  nameEn: string;
  minutes: number;
  servings: number;
  tags: string[];
  season?: string[];
  perServing: Macros;
  ingredientsRo: string[];
  ingredientsEn: string[];
  stepsRo: string[];
  stepsEn: string[];
  imageHue: number;
  imageUrl?: string;
};

export const recipes: Recipe[] = [
  {
    id: "ciorba-radauteana",
    nameRo: "Ciorbă Rădăuțeană de pui",
    nameEn: "Rădăuți chicken soup",
    minutes: 45,
    servings: 4,
    tags: ["pranz", "proteina", "traditional", "popular"],
    perServing: { kcal: 320, protein: 32, carbs: 12, fat: 16 },
    ingredientsRo: [
      "500g piept de pui",
      "2 morcovi, 1 rădăcină țelină",
      "200g smântână 15%",
      "3 gălbenușuri",
      "4 căței usturoi",
      "2 linguri oțet, sare, piper",
    ],
    ingredientsEn: [
      "500g chicken breast",
      "2 carrots, 1 celery root",
      "200g light sour cream (15%)",
      "3 egg yolks",
      "4 garlic cloves",
      "2 tbsp vinegar, salt, pepper",
    ],
    stepsRo: [
      "Fierbe puiul cu legumele până se înmoaie.",
      "Scoate puiul și taie-l fâșii subțiri.",
      "Pasează usturoiul și amestecă-l cu gălbenușurile și smântâna.",
      "Toarnă supa caldă peste amestec, apoi reintrodu puiul și acrește cu oțet.",
    ],
    stepsEn: [
      "Boil chicken with root vegetables until tender.",
      "Shred chicken breast into thin strips.",
      "Whisk egg yolks, sour cream, and crushed garlic.",
      "Temper the cream mix with warm broth, recombine chicken, season with vinegar.",
    ],
    imageHue: 42,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "sarmale-light",
    nameRo: "Sarmale tradiționale light (curcan)",
    nameEn: "Light traditional cabbage rolls (turkey)",
    minutes: 90,
    servings: 6,
    tags: ["traditional", "sarbatori", "proteina"],
    season: ["varza"],
    perServing: { kcal: 290, protein: 24, carbs: 18, fat: 12 },
    ingredientsRo: [
      "600g carne tocată de curcan",
      "1 varză murată mare",
      "80g orez dintr-o bobitță",
      "2 cepe medii, 2 linguri pastă de roșii",
      "cimbru uscat, mărar, piper",
    ],
    ingredientsEn: [
      "600g minced turkey meat",
      "1 large pickled cabbage",
      "80g white rice",
      "2 medium onions, 2 tbsp tomato paste",
      "dried thyme, dill, black pepper",
    ],
    stepsRo: [
      "Călește ușor ceapa și amestecă cu carnea și orezul.",
      "Desfă frunzele de varză și împăturește sarmalele simetric.",
      "Așază-le în oală cu cimbru și pastă de roșii, fierbe 80-90 min.",
    ],
    stepsEn: [
      "Lightly sauté onion and combine with minced turkey and rice.",
      "Roll meat mixture inside sauerkraut leaves.",
      "Layer in pot with thyme and tomato sauce, simmer 80-90 minutes.",
    ],
    imageHue: 15,
    imageUrl: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ciorba-burta",
    nameRo: "Ciorbă de burtă ca la carte",
    nameEn: "Authentic tripe soup",
    minutes: 60,
    servings: 4,
    tags: ["traditional", "pranz", "popular"],
    perServing: { kcal: 340, protein: 26, carbs: 10, fat: 21 },
    ingredientsRo: [
      "600g burtă de vită prefiartă",
      "1 oase de vită pentru supă",
      "200g smântână 15%",
      "2 gălbenușuri, 5 căței usturoi",
      "gogoșari murați, oțet",
    ],
    ingredientsEn: [
      "600g pre-boiled beef tripe",
      "1 marrow beef bone",
      "200g light sour cream",
      "2 egg yolks, 5 garlic cloves",
      "pickled peppers, vinegar",
    ],
    stepsRo: [
      "Fierbe supa concentrată din oase și burtă feliată.",
      "Siropul de usturoi se combină cu smântâna și gălbenușul.",
      "Drege ciorba și servește cu ardei iute și gogoșar.",
    ],
    stepsEn: [
      "Simmer tripe strips in rich beef bone broth.",
      "Whisk garlic paste with egg yolks and sour cream.",
      "Temper into the hot soup and serve with chili & pickled peppers.",
    ],
    imageHue: 35,
    imageUrl: "https://images.unsplash.com/photo-1603105037880-880cd4edfb5d?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "gulas-vita",
    nameRo: "Gulaș de vită ardelenesc",
    nameEn: "Transylvanian beef goulash",
    minutes: 75,
    servings: 4,
    tags: ["pranz", "proteina", "traditional"],
    perServing: { kcal: 430, protein: 38, carbs: 24, fat: 20 },
    ingredientsRo: [
      "600g pulpa de vită",
      "3 cartofi mari",
      "2 cepe, 1 ardei kapia",
      "2 linguri boia dulce de ardei",
      "1 lingură chimen măcinat",
    ],
    ingredientsEn: [
      "600g beef chuck / rump",
      "3 large potatoes",
      "2 onions, 1 sweet pepper",
      "2 tbsp sweet paprika",
      "1 tbsp ground caraway",
    ],
    stepsRo: [
      "Rumenește carnea în cuburi și călește ceapa cu boia.",
      "Adaugă apă, chimen și fierbe la foc mic 50 min până se frăgezește.",
      "Adaugă cartofii cuburi și mai fierbe 20 min până se îngroașă sosul.",
    ],
    stepsEn: [
      "Brown beef cubes and sauté onions with paprika.",
      "Add water, caraway seeds and simmer gently 50 mins until tender.",
      "Add potato cubes and cook 20 mins until rich sauce forms.",
    ],
    imageHue: 20,
    imageUrl: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ostropel-pui",
    nameRo: "Ostropel de pui cu usturoi și piure",
    nameEn: "Garlic chicken ostropel with mashed potatoes",
    minutes: 35,
    servings: 3,
    tags: ["pranz", "cina", "proteina", "popular"],
    perServing: { kcal: 390, protein: 36, carbs: 28, fat: 14 },
    ingredientsRo: [
      "500g ciocănele sau piept de pui",
      "400g roșii pasate",
      "6 căței usturoi pisat",
      "1 lingură ulei, cimbru, pătrunjel proaspăt",
      "400g cartofi pentru piure",
    ],
    ingredientsEn: [
      "500g chicken drumsticks or breast",
      "400g passata tomatoes",
      "6 cloves crushed garlic",
      "1 tbsp oil, thyme, fresh parsley",
      "400g potatoes for mashing",
    ],
    stepsRo: [
      "Rumește puiul în tigaie cu 1 lingură ulei.",
      "Turnă sosul de roșii și usturoiul, lasă să scadă 20 min.",
      "Servește fierbinte peste piure de cartofi presărat cu pătrunjel.",
    ],
    stepsEn: [
      "Brown chicken in a skillet with 1 tbsp oil.",
      "Pour tomato passata and crushed garlic, simmer 20 mins.",
      "Serve hot over fluffy mashed potatoes sprinkled with parsley.",
    ],
    imageHue: 28,
    imageUrl: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "pui-orez",
    nameRo: "Piept de pui la grătar cu orez și salată",
    nameEn: "Grilled chicken breast with rice & salad",
    minutes: 25,
    servings: 2,
    tags: ["pranz", "proteina", "birou", "rapid"],
    perServing: { kcal: 420, protein: 38, carbs: 42, fat: 9 },
    ingredientsRo: [
      "350g piept de pui",
      "120g orez basmati",
      "1 castravete, 2 roșii, ceapă roșie",
      "1 lingură ulei de măsline, lămâie",
    ],
    ingredientsEn: [
      "350g chicken breast",
      "120g basmati rice",
      "1 cucumber, 2 tomatoes, red onion",
      "1 tbsp olive oil, lemon juice",
    ],
    stepsRo: [
      "Fierbe orezul basmati în apă cu puțină sare.",
      "Frige pieptul de pui condimentat pe tigaia grill.",
      "Amestecă legumele tăiate pentru o salată proaspătă.",
    ],
    stepsEn: [
      "Boil basmati rice with a pinch of salt.",
      "Grill seasoned chicken breast until juicy.",
      "Toss diced veggies with olive oil and lemon.",
    ],
    imageHue: 45,
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "pastrav-cuptor",
    nameRo: "Păstrăv la cuptor cu mămăligă și mujdei",
    nameEn: "Baked trout with polenta and garlic mujdei",
    minutes: 25,
    servings: 2,
    tags: ["cina", "proteina", "light", "popular"],
    perServing: { kcal: 360, protein: 38, carbs: 26, fat: 11 },
    ingredientsRo: [
      "2 păstrăvi întregi (aprox. 500g)",
      "1 lămâie, cimbru, rozmarin",
      "100g mălai pentru mămăligă",
      "4 căței usturoi pentru mujdei",
    ],
    ingredientsEn: [
      "2 whole trouts (~500g)",
      "1 lemon, thyme, rosemary",
      "100g cornmeal for polenta",
      "4 garlic cloves for mujdei sauce",
    ],
    stepsRo: [
      "Condimentează păstrăvul cu lămâie și verdețuri, coace 20 min la 200°C.",
      "Prepara mămăliga moale și mujdeiul frecat cu puțină apă și sare.",
      "Servește pe farfurie fierbinte.",
    ],
    stepsEn: [
      "Season trout with lemon and herbs, bake 20 mins at 200°C.",
      "Prepare smooth polenta and garlic mujdei sauce.",
      "Serve hot together.",
    ],
    imageHue: 200,
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "tocanita-ciuperci",
    nameRo: "Tocăniță de ciuperci cu mămăliguță",
    nameEn: "Mushroom stew with creamy polenta",
    minutes: 30,
    servings: 3,
    tags: ["post", "ieftin", "cina", "vegetarian"],
    season: ["ciuperci"],
    perServing: { kcal: 280, protein: 10, carbs: 42, fat: 8 },
    ingredientsRo: [
      "500g ciuperci champignon / hribi",
      "2 cepe, 4 căței usturoi",
      "200ml bulion de roșii",
      "1 lingură ulei, mărar proaspăt",
      "120g mălai",
    ],
    ingredientsEn: [
      "500g button mushrooms or porcini",
      "2 onions, 4 garlic cloves",
      "200ml tomato passata",
      "1 tbsp oil, fresh dill",
      "120g cornmeal",
    ],
    stepsRo: [
      "Călește ceapa și ciupercile felii până scade apa.",
      "Adaugă usturoiul, bulionul și fierbe 15 min.",
      "Servește cu mămăligă caldă presărată cu mărar.",
    ],
    stepsEn: [
      "Sauté onions and sliced mushrooms until moisture evaporates.",
      "Add garlic and tomato passata, simmer 15 mins.",
      "Serve over warm polenta garnished with dill.",
    ],
    imageHue: 80,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "salata-vinete",
    nameRo: "Salată de vinete coapte cu roșii",
    nameEn: "Roasted eggplant salad with tomatoes",
    minutes: 25,
    servings: 3,
    tags: ["gustare", "light", "traditional", "post"],
    season: ["vinete", "rosii"],
    perServing: { kcal: 190, protein: 4, carbs: 14, fat: 13 },
    ingredientsRo: [
      "2 vinete mari coapte și scurse",
      "1 ceapă galbenă mică tocată fin",
      "2 linguri ulei de floarea soarelui",
      "2 roșii proaspete feliate",
      "sare după gust",
    ],
    ingredientsEn: [
      "2 large roasted & drained eggplants",
      "1 small finely chopped yellow onion",
      "2 tbsp sunflower oil",
      "2 fresh sliced tomatoes",
      "salt to taste",
    ],
    stepsRo: [
      "Tacă vinetele coapte cu un tocător de lemn.",
      "Incorporează ceapa tocată fin și toarnă uleiul treptat frecând energic.",
      "Servește rece cu felii de roșii și pâine neagră.",
    ],
    stepsEn: [
      "Chop roasted eggplants finely using a wooden knife.",
      "Mix in chopped onion and drizzle oil while stirring constantly.",
      "Serve chilled with sliced ripe tomatoes.",
    ],
    imageHue: 110,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "omleta-telemea",
    nameRo: "Omletă puffy cu telemea și mărar",
    nameEn: "Fluffy omelette with telemea cheese & dill",
    minutes: 12,
    servings: 1,
    tags: ["mic-dejun", "rapid", "proteina", "popular"],
    perServing: { kcal: 320, protein: 22, carbs: 3, fat: 24 },
    ingredientsRo: [
      "3 ouă proaspete",
      "40g telemea de vacă sau oaie",
      "mărar și ceapă verde tocată",
      "1 linguriță unt / ulei",
    ],
    ingredientsEn: [
      "3 fresh eggs",
      "40g Romanian telemea cheese",
      "chopped dill & green onion",
      "1 tsp butter or oil",
    ],
    stepsRo: [
      "Bate ouăle spumă cu un praf de sare și mărar.",
      "Toarnă în tigaie încinsă și presară telemeaua sfărâmată.",
      "Rulează omleta când este rumenă.",
    ],
    stepsEn: [
      "Whisk eggs with a pinch of salt and fresh dill.",
      "Pour into hot skillet and sprinkle crumbled telemea.",
      "Fold into a fluffy omelette.",
    ],
    imageHue: 48,
    imageUrl: "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ovaz-napolact",
    nameRo: "Ovăz proteic cu iaurt Napolact și măr",
    nameEn: "Protein oats with Napolact yogurt & apple",
    minutes: 8,
    servings: 1,
    tags: ["mic-dejun", "rapid", "ieftin"],
    season: ["mere"],
    perServing: { kcal: 340, protein: 16, carbs: 52, fat: 8 },
    ingredientsRo: [
      "50g fulgi de ovăz fini",
      "150g iaurt natural Napolact 3.5%",
      "1 măr Ionatan ras",
      "1 linguriță miere, scorțișoară",
    ],
    ingredientsEn: [
      "50g fine oat flakes",
      "150g Napolact natural yogurt 3.5%",
      "1 grated red apple",
      "1 tsp honey, cinnamon",
    ],
    stepsRo: [
      "Amestecă ovăzul cu iaurtul proaspăt.",
      "Adaugă mărul ras și scorțișoara.",
      "Lasă 5 minute să se hidrateze și servește.",
    ],
    stepsEn: [
      "Combine oats with fresh yogurt.",
      "Fold in grated apple and cinnamon.",
      "Rest for 5 mins to soften, then enjoy.",
    ],
    imageHue: 40,
    imageUrl: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ciorba-legume",
    nameRo: "Ciorbă țărănească de legume cu borș",
    nameEn: "Peasant vegetable soup with sour borș",
    minutes: 40,
    servings: 4,
    tags: ["pranz", "light", "ieftin", "post"],
    season: ["varza", "morcov", "telina"],
    perServing: { kcal: 180, protein: 6, carbs: 28, fat: 5 },
    ingredientsRo: [
      "300g varză dulce",
      "2 morcovi, 1 păstârnac",
      "1 ceapă, 100g mazăre",
      "500ml borș acru de casă",
      "leuștean proaspăt",
    ],
    ingredientsEn: [
      "300g cabbage",
      "2 carrots, 1 parsnip",
      "1 onion, 100g green peas",
      "500ml fermented rye borș",
      "fresh lovage",
    ],
    stepsRo: [
      "Fierbe legumele tocate în apă cu sare 25 min.",
      "Adaugă borșul dat în clocot separat.",
      "Oprește focul și presară mult leuștean verde.",
    ],
    stepsEn: [
      "Simmer chopped root vegetables 25 mins.",
      "Pour boiled borș sour liquid.",
      "Turn off heat and top generously with fresh lovage.",
    ],
    imageHue: 95,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "dovlecei-umpluti",
    nameRo: "Dovlecei umpluți cu carne de curcan",
    nameEn: "Stuffed zucchini with minced turkey",
    minutes: 45,
    servings: 4,
    tags: ["cina", "proteina", "light"],
    season: ["dovlecei"],
    perServing: { kcal: 290, protein: 26, carbs: 16, fat: 13 },
    ingredientsRo: [
      "4 dovlecei medii scobiți",
      "400g carne tocată de curcan",
      "1 ceapă, 50g orez",
      "300ml bulion de roșii, mărar",
    ],
    ingredientsEn: [
      "4 hollowed medium zucchinis",
      "400g minced turkey meat",
      "1 onion, 50g rice",
      "300ml tomato sauce, dill",
    ],
    stepsRo: [
      "Umple dovleceii cu amestecul de carne, ceapă și orez.",
      "Așază-i în tavă adâncă și toarnă bulionul de roșii.",
      "Coace la cuptor 40 min la 190°C.",
    ],
    stepsEn: [
      "Stuff zucchinis with turkey, onion and rice mix.",
      "Arrange in baking dish, add tomato sauce.",
      "Bake for 40 mins at 190°C.",
    ],
    imageHue: 120,
    imageUrl: "https://images.unsplash.com/photo-1592417817098-8f3d6eb19657?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "bulz-ardelenesc",
    nameRo: "Bulz ardelenesc copt la cuptor",
    nameEn: "Baked Transylvanian polenta bulz",
    minutes: 30,
    servings: 2,
    tags: ["traditional", "popular", "cina"],
    perServing: { kcal: 410, protein: 20, carbs: 36, fat: 22 },
    ingredientsRo: [
      "150g mălai pentru mămăligă pripită",
      "80g telemea de oaie sau burduf",
      "2 ouă ochiuri / fierte",
      "1 lingură unt",
    ],
    ingredientsEn: [
      "150g cornmeal for thick polenta",
      "80g sheep burduf or telemea cheese",
      "2 eggs",
      "1 tbsp butter",
    ],
    stepsRo: [
      "Prepara o mămăligă teapănă și formează două bile mari.",
      "Umple mijlocul cu brânză de burduf și unt.",
      "Coace la cuptor 15 min și servește cu ou ochi deasupra.",
    ],
    stepsEn: [
      "Make thick polenta and shape into two balls.",
      "Stuff centers with rich sheep cheese and butter.",
      "Bake 15 mins and crown with a fried egg.",
    ],
    imageHue: 30,
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "salata-ton",
    nameRo: "Salată proteică cu ton Scandia și ou",
    nameEn: "Protein salad with Scandia tuna & egg",
    minutes: 10,
    servings: 1,
    tags: ["pranz", "proteina", "birou", "rapid"],
    perServing: { kcal: 310, protein: 32, carbs: 12, fat: 14 },
    ingredientsRo: [
      "1 conservă ton Scandia în suc propriu",
      "1 ou fiert tare",
      "mix salată verde, castravete, porumb",
      "1 lingură ulei de măsline",
    ],
    ingredientsEn: [
      "1 can Scandia tuna in brine",
      "1 hard-boiled egg",
      "salad greens, cucumber, sweetcorn",
      "1 tbsp olive oil",
    ],
    stepsRo: [
      "Scurge tonul și taie ouăle feliuțe.",
      "Amestecă toate ingredientele proaspete în bol.",
      "Stropește cu ulei de măsline și zeamă de lămâie.",
    ],
    stepsEn: [
      "Drain tuna and slice boiled egg.",
      "Toss all fresh ingredients in bowl.",
      "Drizzle olive oil and lemon juice.",
    ],
    imageHue: 180,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "placinta-branza",
    nameRo: "Plăcintă cu brânză dulce și stafide",
    nameEn: "Sweet cheese & raisin pie",
    minutes: 40,
    servings: 6,
    tags: ["desert", "traditional"],
    perServing: { kcal: 340, protein: 14, carbs: 38, fat: 15 },
    ingredientsRo: [
      "1 pachet foi de plăcintă subțiri",
      "400g brânză dulce de vaci",
      "3 ouă, 80g stafide inmuiate",
      "2 plicuri zahăr vanilat, coajă de lămâie",
    ],
    ingredientsEn: [
      "1 pack thin phyllo sheets",
      "400g sweet cottage cheese",
      "3 eggs, 80g soaked raisins",
      "vanilla sugar, lemon zest",
    ],
    stepsRo: [
      "Amestecă brânza cu ouăle, stafidele și vanilia.",
      "Așază foile unse ușor cu ulei, adaugă umplutura și rulează.",
      "Coace la 180°C timp de 35 min până devine aurie.",
    ],
    stepsEn: [
      "Whisk cottage cheese with eggs, raisins and vanilla zest.",
      "Layer phyllo pastry, spread filling and roll up.",
      "Bake at 180°C for 35 mins until golden brown.",
    ],
    imageHue: 38,
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80",
  },
];

export function recipeName(recipe: Recipe, locale: "ro" | "en") {
  return locale === "ro" ? recipe.nameRo : recipe.nameEn;
}

