import type { Macros } from "./foods";

export type Recipe = {
  id: string;
  nameRo: string;
  nameEn: string;
  minutes: number;
  servings: number;
  tags: string[];
  season?: string[];
  perServing: Macros;
  ingredientsRo: string[];
  ingredientsEn: string[];
  stepsRo: string[];
  stepsEn: string[];
  imageHue: number;
  imageUrl?: string;
};

export const recipes: Recipe[] = [
  // ==========================================
  // MIC DEJUN (14 REȚETE)
  // ==========================================
  {
    id: "ovaz-napolact",
    nameRo: "Ovăz proteic cu iaurt natural și măr",
    nameEn: "Protein oats with natural yogurt & apple",
    minutes: 8,
    servings: 1,
    tags: ["mic-dejun", "rapid", "ieftin", "proteina"],
    season: ["mere"],
    perServing: { kcal: 340, protein: 16, carbs: 52, fat: 8 },
    ingredientsRo: [
      "50g fulgi de ovăz fini",
      "150g iaurt natural 3.5%",
      "1 măr Ionatan ras",
      "1 linguriță miere, scorțișoară",
    ],
    ingredientsEn: [
      "50g fine oat flakes",
      "150g natural yogurt 3.5%",
      "1 grated red apple",
      "1 tsp honey, cinnamon",
    ],
    stepsRo: [
      "Amestecă ovăzul cu iaurtul proaspăt.",
      "Adaugă mărul ras și scorțișoara.",
      "Lasă 5 minute să se hidrateze și servește.",
    ],
    stepsEn: [
      "Combine oats with fresh yogurt.",
      "Fold in grated apple and cinnamon.",
      "Rest for 5 mins to soften, then enjoy.",
    ],
    imageHue: 40,
    imageUrl: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "omleta-telemea",
    nameRo: "Omletă puffy cu telemea și mărar",
    nameEn: "Fluffy omelette with telemea cheese & dill",
    minutes: 12,
    servings: 1,
    tags: ["mic-dejun", "rapid", "proteina", "traditional"],
    perServing: { kcal: 320, protein: 22, carbs: 3, fat: 24 },
    ingredientsRo: [
      "3 ouă proaspete",
      "40g telemea de vacă sau oaie",
      "mărar și ceapă verde tocată",
      "1 linguriță unt / ulei",
    ],
    ingredientsEn: [
      "3 fresh eggs",
      "40g Romanian telemea cheese",
      "chopped dill & green onion",
      "1 tsp butter or oil",
    ],
    stepsRo: [
      "Bate ouăle spumă cu un praf de sare și mărar.",
      "Toarnă în tigaie încinsă și presară telemeaua sfărâmată.",
      "Rulează omleta când este rumenă.",
    ],
    stepsEn: [
      "Whisk eggs with a pinch of salt and fresh dill.",
      "Pour into hot skillet and sprinkle crumbled telemea.",
      "Fold into a fluffy omelette.",
    ],
    imageHue: 48,
    imageUrl: "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "pancakes-banane",
    nameRo: "Clătite americane cu banane și ovăz",
    nameEn: "Banana oat protein pancakes",
    minutes: 15,
    servings: 2,
    tags: ["mic-dejun", "international", "proteina", "popular"],
    perServing: { kcal: 350, protein: 18, carbs: 54, fat: 6 },
    ingredientsRo: [
      "2 banane coapte",
      "2 ouă",
      "80g fulgi de ovăz măcinați",
      "100ml lapte",
      "1/2 linguriță praf de copt, vanilie",
    ],
    ingredientsEn: [
      "2 ripe bananas",
      "2 eggs",
      "80g oat flour",
      "100ml milk",
      "1/2 tsp baking powder, vanilla",
    ],
    stepsRo: [
      "Pasează banana cu furculița și amestecă cu ouăle și ovăzul.",
      "Toarnă polonice mici în tigaia antiaderentă încinsă.",
      "Coace 2 min pe fiecare parte până devin aurii.",
    ],
    stepsEn: [
      "Mash bananas and blend with eggs, milk, and oat flour.",
      "Ladle small pancakes onto a hot non-stick skillet.",
      "Cook 2 mins per side until golden brown.",
    ],
    imageHue: 30,
    imageUrl: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "avocado-toast-ou",
    nameRo: "Avocado Toast cu ou poșat",
    nameEn: "Avocado toast with poached egg",
    minutes: 10,
    servings: 1,
    tags: ["mic-dejun", "international", "rapid", "popular"],
    perServing: { kcal: 310, protein: 14, carbs: 26, fat: 17 },
    ingredientsRo: [
      "1 felie pâine neagră / maia",
      "1/2 avocado copt",
      "1 ou proaspăt",
      "lămâie, fulgi de ardei iute, susan",
    ],
    ingredientsEn: [
      "1 slice sourdough or dark bread",
      "1/2 ripe avocado",
      "1 fresh egg",
      "lemon juice, chili flakes, sesame seeds",
    ],
    stepsRo: [
      "Prăjește pâinea și zdrobește avocado cu zeamă de lămâie.",
      "Fierbe oul în apă cu un strop de oțet timp de 3 minute.",
      "Așază oul poșat peste avocado și presară fulgi de ardei.",
    ],
    stepsEn: [
      "Toast the sourdough bread and mash avocado with lemon.",
      "Poach the egg in simmering water with vinegar for 3 mins.",
      "Top toast with poached egg and sprinkle chili flakes.",
    ],
    imageHue: 100,
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "shakshuka-mediteraneana",
    nameRo: "Shakshuka mediteraneană cu ouă",
    nameEn: "Mediterranean Shakshuka with poached eggs",
    minutes: 20,
    servings: 2,
    tags: ["mic-dejun", "international", "popular"],
    perServing: { kcal: 280, protein: 16, carbs: 18, fat: 16 },
    ingredientsRo: [
      "3 ouă",
      "400g roșii zemoase / cuburi",
      "1 ardei roșu, 1 ceapă, 2 căței usturoi",
      "1 lingură ulei măsline, chimen, pătrunjel",
    ],
    ingredientsEn: [
      "3 eggs",
      "400g canned diced tomatoes",
      "1 red bell pepper, 1 onion, 2 garlic cloves",
      "1 tbsp olive oil, cumin, fresh parsley",
    ],
    stepsRo: [
      "Călește ceapa, ardeiul și usturoiul în ulei de măsline.",
      "Adaugă roșiile și condimentele, lasă să scadă 10 min.",
      "Fă spații în sos, sparge ouăle și acoperă 5 min până se încheagă albușul.",
    ],
    stepsEn: [
      "Sauté onion, pepper and garlic in olive oil.",
      "Pour tomatoes and spices, simmer 10 mins.",
      "Make wells, crack eggs in and cover for 5 mins until whites set.",
    ],
    imageHue: 18,
    imageUrl: "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "chia-pudding-afine",
    nameRo: "Puding de chia cu lapte de migdale și afine",
    nameEn: "Chia seed pudding with almond milk & blueberries",
    minutes: 5,
    servings: 1,
    tags: ["mic-dejun", "international", "post", "light"],
    perServing: { kcal: 240, protein: 8, carbs: 28, fat: 11 },
    ingredientsRo: [
      "30g semințe de chia",
      "200ml lapte de migdale nesărat",
      "50g afine proaspete",
      "1 linguriță sirop de arțar / miere",
    ],
    ingredientsEn: [
      "30g chia seeds",
      "200ml unsweetened almond milk",
      "50g fresh blueberries",
      "1 tsp maple syrup or honey",
    ],
    stepsRo: [
      "Amestecă semințele de chia cu laptele de migdale și îndulcitorul.",
      "Lasă la frigider cel puțin 20 de minute (sau peste noapte).",
      "Ornează cu afine proaspete înainte de servire.",
    ],
    stepsEn: [
      "Whisk chia seeds with almond milk and sweetener.",
      "Refrigerate for at least 20 mins (or overnight).",
      "Top with fresh blueberries before serving.",
    ],
    imageHue: 240,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "frittata-spanac",
    nameRo: "Frittata italiană cu spanac și ricotta",
    nameEn: "Italian spinach & ricotta frittata",
    minutes: 18,
    servings: 2,
    tags: ["mic-dejun", "international", "proteina"],
    perServing: { kcal: 290, protein: 20, carbs: 6, fat: 21 },
    ingredientsRo: [
      "4 ouă",
      "150g spanac proaspăt",
      "60g brânză ricotta / urdă",
      "1 lingură parmezan ras, nucșoară",
    ],
    ingredientsEn: [
      "4 eggs",
      "150g fresh baby spinach",
      "60g ricotta cheese",
      "1 tbsp grated parmesan, nutmeg",
    ],
    stepsRo: [
      "Sotează spanacul în tigaie până scade.",
      "Bate ouăle cu parmezanul și toarnă peste spanac.",
      "Adaugă cuiburi de ricotta și coace la foc mic sub capac 8-10 min.",
    ],
    stepsEn: [
      "Sauté spinach in skillet until wilted.",
      "Beat eggs with parmesan and pour over spinach.",
      "Dollop ricotta and cook covered on low heat for 8-10 mins.",
    ],
    imageHue: 120,
    imageUrl: "https://images.unsplash.com/photo-1584776296944-ab6fb57b0bff?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "boul-smoothie-capsuni",
    nameRo: "Smoothie Bowl proteic cu căpșuni și granola",
    nameEn: "Strawberry protein smoothie bowl",
    minutes: 7,
    servings: 1,
    tags: ["mic-dejun", "international", "proteina", "rapid"],
    perServing: { kcal: 330, protein: 24, carbs: 46, fat: 6 },
    ingredientsRo: [
      "150g căpșuni congelate",
      "150g iaurt grecesc 2%",
      "30g pudră proteică (vanilie/fără aromă)",
      "20g granola crocantă",
    ],
    ingredientsEn: [
      "150g frozen strawberries",
      "150g Greek yogurt 2%",
      "30g protein powder (vanilla/unflavored)",
      "20g crunchy granola",
    ],
    stepsRo: [
      "Pasează la blender căpșunile, iaurtul și pudra proteică.",
      "Toarnă compoziția cremoasă într-un bol.",
      "Presară granola și felii de fructe proaspete.",
    ],
    stepsEn: [
      "Blend frozen strawberries, yogurt and protein powder until thick.",
      "Pour smooth mixture into a serving bowl.",
      "Top with crunchy granola and fresh berry slices.",
    ],
    imageHue: 340,
    imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ou-benedict-somon",
    nameRo: "Ouă Benedict cu somon afumat",
    nameEn: "Eggs Benedict with smoked salmon",
    minutes: 15,
    servings: 1,
    tags: ["mic-dejun", "international", "popular", "proteina"],
    perServing: { kcal: 380, protein: 26, carbs: 24, fat: 20 },
    ingredientsRo: [
      "1 chiflă englezească / brioșă integrală",
      "50g somon afumat feliat",
      "1 ou poșat",
      "1 lingură iaurt grecesc frecat cu zeamă de lămâie și mărar",
    ],
    ingredientsEn: [
      "1 English muffin or wholewheat bun",
      "50g sliced smoked salmon",
      "1 poached egg",
      "1 tbsp Greek yogurt sauce with lemon and dill",
    ],
    stepsRo: [
      "Prăjește jumătățile de chiflă.",
      "Așază felia de somon afumat și oul poșat moale.",
      "Toarnă sosul light de iaurt și lămâie deasupra.",
    ],
    stepsEn: [
      "Toast muffin halves lightly.",
      "Layer smoked salmon and warm poached egg.",
      "Drizzle with light yogurt lemon dill sauce.",
    ],
    imageHue: 35,
    imageUrl: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "burrito-mic-dejun",
    nameRo: "Burrito de mic dejun cu ouă jumări și avocado",
    nameEn: "Breakfast burrito with scrambled eggs & avocado",
    minutes: 12,
    servings: 1,
    tags: ["mic-dejun", "international", "rapid", "proteina"],
    perServing: { kcal: 420, protein: 22, carbs: 38, fat: 20 },
    ingredientsRo: [
      "1 lipie integrală",
      "2 ouă jumări cremoase",
      "1/3 avocado feliat",
      "30g brânză Cheddar rasă, salsa de roșii",
    ],
    ingredientsEn: [
      "1 wholewheat tortilla wrap",
      "2 creamy scrambled eggs",
      "1/3 sliced avocado",
      "30g shredded Cheddar, tomato salsa",
    ],
    stepsRo: [
      "Pregătește ouăle jumări în tigaie.",
      "Încălzește lipia, adaugă ouăle, avocado, brânza și salsa.",
      "Rulează strâns burrito și rumenește pe ambele părți 1 min.",
    ],
    stepsEn: [
      "Scramble eggs gently in a pan.",
      "Warm tortilla, fill with eggs, avocado, cheese and salsa.",
      "Roll up tightly and sear both sides in a skillet.",
    ],
    imageHue: 25,
    imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "vafe-branza-cottage",
    nameRo: "Vafe proteice din brânză cottage și ovăz",
    nameEn: "Cottage cheese & oat waffles",
    minutes: 15,
    servings: 2,
    tags: ["mic-dejun", "international", "proteina"],
    perServing: { kcal: 310, protein: 28, carbs: 32, fat: 7 },
    ingredientsRo: [
      "200g brânză cottage / perle de brânză",
      "80g ovăz măcinat",
      "2 ouă",
      "1/2 linguriță praf de copt, coajă de lămâie",
    ],
    ingredientsEn: [
      "200g cottage cheese",
      "80g ground oat flour",
      "2 eggs",
      "1/2 tsp baking powder, lemon zest",
    ],
    stepsRo: [
      "Pasează la blender brânza cottage, ovăzul și ouăle până obții un aluat fin.",
      "Toarnă în aparatul de vafe încins și uns cu puțin unt.",
      "Coace 5-6 min până devin aurii și crocante.",
    ],
    stepsEn: [
      "Blend cottage cheese, oat flour, and eggs until smooth batter forms.",
      "Pour into hot greased waffle iron.",
      "Bake 5-6 mins until crisp and golden.",
    ],
    imageHue: 42,
    imageUrl: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ochiuri-bacon-avocado",
    nameRo: "Mic dejun Keto: Ouă ochiuri cu bacon și avocado",
    nameEn: "Keto breakfast: Fried eggs, bacon & avocado",
    minutes: 10,
    servings: 1,
    tags: ["mic-dejun", "international", "rapid", "proteina"],
    perServing: { kcal: 410, protein: 22, carbs: 4, fat: 34 },
    ingredientsRo: [
      "2 ouă proaspete",
      "2 felii subțiri de bacon crocant",
      "1/2 avocado copt feliat",
      "1 linguriță unt, sare, piper",
    ],
    ingredientsEn: [
      "2 fresh eggs",
      "2 thin crispy bacon strips",
      "1/2 sliced ripe avocado",
      "1 tsp butter, salt, pepper",
    ],
    stepsRo: [
      "Prăjește baconul până devine crocant.",
      "Gătește ouăle ochiuri în unt cu gălbenușul moale.",
      "Servește alături de felii de avocado presărate cu sare marină.",
    ],
    stepsEn: [
      "Fry bacon strips until crispy.",
      "Cook sunny-side-up eggs in butter until whites set.",
      "Serve alongside sliced avocado with sea salt.",
    ],
    imageHue: 15,
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "porridge-ciocolata-arahide",
    nameRo: "Porridge cremos de ciocolată cu unt de arahide",
    nameEn: "Creamy chocolate peanut butter porridge",
    minutes: 8,
    servings: 1,
    tags: ["mic-dejun", "international", "rapid"],
    perServing: { kcal: 360, protein: 14, carbs: 50, fat: 12 },
    ingredientsRo: [
      "50g ovăz",
      "250ml lapte sau apă",
      "1 lingură pudră de cacao neagră",
      "1 lingură unt de arahide natural",
      "1 linguriță miere",
    ],
    ingredientsEn: [
      "50g oats",
      "250ml milk or water",
      "1 tbsp dark cocoa powder",
      "1 tbsp natural peanut butter",
      "1 tsp honey",
    ],
    stepsRo: [
      "Fierbe ovăzul în lapte cu pudra de cacao 4-5 minute.",
      "Oprește focul și încorporează untul de arahide cremos.",
      "Îndulcește cu miere și servește cald.",
    ],
    stepsEn: [
      "Simmer oats in milk with cocoa powder for 4-5 mins.",
      "Stir in natural creamy peanut butter.",
      "Sweeten with honey and enjoy warm.",
    ],
    imageHue: 18,
    imageUrl: "https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "sandwich-club-curcan",
    nameRo: "Sandwich Club cu curcan și ou fiert",
    nameEn: "Turkey & egg Club Sandwich",
    minutes: 10,
    servings: 1,
    tags: ["mic-dejun", "international", "rapid", "proteina"],
    perServing: { kcal: 390, protein: 30, carbs: 36, fat: 14 },
    ingredientsRo: [
      "2 felii pâine toast integrală",
      "60g șuncă / piept de curcan feliat",
      "1 ou fiert feliat",
      "salată verde, roșie, 1 linguriță sos iaurt cu muștar",
    ],
    ingredientsEn: [
      "2 slices wholewheat toast",
      "60g sliced turkey breast ham",
      "1 hard-boiled egg sliced",
      "lettuce, tomato, 1 tsp yogurt mustard sauce",
    ],
    stepsRo: [
      "Prăjește feliile de pâine integrală.",
      "Așază sosul de iaurt, salata, felii de roșie, curcanul și oul.",
      "Taie sandwich-ul pe diagonală și servește.",
    ],
    stepsEn: [
      "Toast wholewheat bread slices.",
      "Layer yogurt mustard, lettuce, tomato, turkey ham, and egg slices.",
      "Cut diagonally and serve.",
    ],
    imageHue: 40,
    imageUrl: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80",
  },

  // ==========================================
  // PRÂNZ (15 REȚETE)
  // ==========================================
  {
    id: "ciorba-radauteana",
    nameRo: "Ciorbă Rădăuțeană de pui",
    nameEn: "Rădăuți chicken soup",
    minutes: 45,
    servings: 4,
    tags: ["pranz", "proteina", "traditional", "popular"],
    perServing: { kcal: 320, protein: 32, carbs: 12, fat: 16 },
    ingredientsRo: [
      "500g piept de pui",
      "2 morcovi, 1 rădăcină țelină",
      "200g smântână 15%",
      "3 gălbenușuri",
      "4 căței usturoi",
      "2 linguri oțet, sare, piper",
    ],
    ingredientsEn: [
      "500g chicken breast",
      "2 carrots, 1 celery root",
      "200g light sour cream (15%)",
      "3 egg yolks",
      "4 garlic cloves",
      "2 tbsp vinegar, salt, pepper",
    ],
    stepsRo: [
      "Fierbe puiul cu legumele până se înmoaie.",
      "Scoate puiul și taie-l fâșii subțiri.",
      "Pasează usturoiul și amestecă-l cu gălbenușurile și smântâna.",
      "Toarnă supa caldă peste amestec, apoi reintrodu puiul și acrește cu oțet.",
    ],
    stepsEn: [
      "Boil chicken with root vegetables until tender.",
      "Shred chicken breast into thin strips.",
      "Whisk egg yolks, sour cream, and crushed garlic.",
      "Temper the cream mix with warm broth, recombine chicken, season with vinegar.",
    ],
    imageHue: 42,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ciorba-burta",
    nameRo: "Ciorbă de burtă ca la carte",
    nameEn: "Authentic tripe soup",
    minutes: 60,
    servings: 4,
    tags: ["traditional", "pranz", "popular"],
    perServing: { kcal: 340, protein: 26, carbs: 10, fat: 21 },
    ingredientsRo: [
      "600g burtă de vită prefiartă",
      "1 oase de vită pentru supă",
      "200g smântână 15%",
      "2 gălbenușuri, 5 căței usturoi",
      "gogoșari murați, oțet",
    ],
    ingredientsEn: [
      "600g pre-boiled beef tripe",
      "1 marrow beef bone",
      "200g light sour cream",
      "2 egg yolks, 5 garlic cloves",
      "pickled peppers, vinegar",
    ],
    stepsRo: [
      "Fierbe supa concentrată din oase și burtă feliată.",
      "Siropul de usturoi se combină cu smântâna și gălbenușul.",
      "Drege ciorba și servește cu ardei iute și gogoșar.",
    ],
    stepsEn: [
      "Simmer tripe strips in rich beef bone broth.",
      "Whisk garlic paste with egg yolks and sour cream.",
      "Temper into the hot soup and serve with chili & pickled peppers.",
    ],
    imageHue: 35,
    imageUrl: "https://images.unsplash.com/photo-1603105037880-880cd4edfb5d?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "gulas-vita",
    nameRo: "Gulaș de vită ardelenesc",
    nameEn: "Transylvanian beef goulash",
    minutes: 75,
    servings: 4,
    tags: ["pranz", "proteina", "traditional"],
    perServing: { kcal: 430, protein: 38, carbs: 24, fat: 20 },
    ingredientsRo: [
      "600g pulpa de vită",
      "3 cartofi mari",
      "2 cepe, 1 ardei kapia",
      "2 linguri boia dulce de ardei",
      "1 lingură chimen măcinat",
    ],
    ingredientsEn: [
      "600g beef chuck / rump",
      "3 large potatoes",
      "2 onions, 1 sweet pepper",
      "2 tbsp sweet paprika",
      "1 tbsp ground caraway",
    ],
    stepsRo: [
      "Rumenește carnea în cuburi și călește ceapa cu boia.",
      "Adaugă apă, chimen și fierbe la foc mic 50 min până se frăgezește.",
      "Adaugă cartofii cuburi și mai fierbe 20 min până se îngroașă sosul.",
    ],
    stepsEn: [
      "Brown beef cubes and sauté onions with paprika.",
      "Add water, caraway seeds and simmer gently 50 mins until tender.",
      "Add potato cubes and cook 20 mins until rich sauce forms.",
    ],
    imageHue: 20,
    imageUrl: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ostropel-pui",
    nameRo: "Ostropel de pui cu usturoi și piure",
    nameEn: "Garlic chicken ostropel with mashed potatoes",
    minutes: 35,
    servings: 3,
    tags: ["pranz", "cina", "proteina", "popular"],
    perServing: { kcal: 390, protein: 36, carbs: 28, fat: 14 },
    ingredientsRo: [
      "500g ciocănele sau piept de pui",
      "400g roșii pasate",
      "6 căței usturoi pisat",
      "1 lingură ulei, cimbru, pătrunjel proaspăt",
      "400g cartofi pentru piure",
    ],
    ingredientsEn: [
      "500g chicken drumsticks or breast",
      "400g passata tomatoes",
      "6 cloves crushed garlic",
      "1 tbsp oil, thyme, fresh parsley",
      "400g potatoes for mashing",
    ],
    stepsRo: [
      "Rumește puiul în tigaie cu 1 lingură ulei.",
      "Turnă sosul de roșii și usturoiul, lasă să scadă 20 min.",
      "Servește fierbinte peste piure de cartofi presărat cu pătrunjel.",
    ],
    stepsEn: [
      "Brown chicken in a skillet with 1 tbsp oil.",
      "Pour tomato passata and crushed garlic, simmer 20 mins.",
      "Serve hot over fluffy mashed potatoes sprinkled with parsley.",
    ],
    imageHue: 28,
    imageUrl: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "pui-orez",
    nameRo: "Piept de pui la grătar cu orez și salată",
    nameEn: "Grilled chicken breast with rice & salad",
    minutes: 25,
    servings: 2,
    tags: ["pranz", "proteina", "birou", "rapid"],
    perServing: { kcal: 420, protein: 38, carbs: 42, fat: 9 },
    ingredientsRo: [
      "350g piept de pui",
      "120g orez basmati",
      "1 castravete, 2 roșii, ceapă roșie",
      "1 lingură ulei de măsline, lămâie",
    ],
    ingredientsEn: [
      "350g chicken breast",
      "120g basmati rice",
      "1 cucumber, 2 tomatoes, red onion",
      "1 tbsp olive oil, lemon juice",
    ],
    stepsRo: [
      "Fierbe orezul basmati în apă cu puțină sare.",
      "Frige pieptul de pui condimentat pe tigaia grill.",
      "Amestecă legumele tăiate pentru o salată proaspătă.",
    ],
    stepsEn: [
      "Boil basmati rice with a pinch of salt.",
      "Grill seasoned chicken breast until juicy.",
      "Toss diced veggies with olive oil and lemon.",
    ],
    imageHue: 45,
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ciorba-legume",
    nameRo: "Ciorbă țărănească de legume cu borș",
    nameEn: "Peasant vegetable soup with sour borș",
    minutes: 40,
    servings: 4,
    tags: ["pranz", "light", "ieftin", "post"],
    season: ["varza", "morcov", "telina"],
    perServing: { kcal: 180, protein: 6, carbs: 28, fat: 5 },
    ingredientsRo: [
      "300g varză dulce",
      "2 morcovi, 1 păstârnac",
      "1 ceapă, 100g mazăre",
      "500ml borș acru de casă",
      "leuștean proaspăt",
    ],
    ingredientsEn: [
      "300g cabbage",
      "2 carrots, 1 parsnip",
      "1 onion, 100g green peas",
      "500ml fermented rye borș",
      "fresh lovage",
    ],
    stepsRo: [
      "Fierbe legumele tocate în apă cu sare 25 min.",
      "Adaugă borșul dat în clocot separat.",
      "Oprește focul și presară mult leuștean verde.",
    ],
    stepsEn: [
      "Simmer chopped root vegetables 25 mins.",
      "Pour boiled borș sour liquid.",
      "Turn off heat and top generously with fresh lovage.",
    ],
    imageHue: 95,
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "salata-ton",
    nameRo: "Salată proteică cu ton și ou",
    nameEn: "Protein salad with tuna & egg",
    minutes: 10,
    servings: 1,
    tags: ["pranz", "proteina", "birou", "rapid"],
    perServing: { kcal: 310, protein: 32, carbs: 12, fat: 14 },
    ingredientsRo: [
      "1 conservă ton în suc propriu",
      "1 ou fiert tare",
      "mix salată verde, castravete, porumb",
      "1 lingură ulei de măsline",
    ],
    ingredientsEn: [
      "1 can tuna in brine",
      "1 hard-boiled egg",
      "salad greens, cucumber, sweetcorn",
      "1 tbsp olive oil",
    ],
    stepsRo: [
      "Scurge tonul și taie ouăle feliuțe.",
      "Amestecă toate ingredientele proaspete în bol.",
      "Stropește cu ulei de măsline și zeamă de lămâie.",
    ],
    stepsEn: [
      "Drain tuna and slice boiled egg.",
      "Toss all fresh ingredients in bowl.",
      "Drizzle olive oil and lemon juice.",
    ],
    imageHue: 180,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "pasta-carbonara-fit",
    nameRo: "Paste italienești Carbonara (Light)",
    nameEn: "Italian pasta Carbonara (Light)",
    minutes: 20,
    servings: 2,
    tags: ["pranz", "international", "popular", "proteina"],
    perServing: { kcal: 460, protein: 28, carbs: 52, fat: 16 },
    ingredientsRo: [
      "160g paste spaghetti integrale",
      "80g guanciale sau pancetta / bacon slab",
      "2 gălbenușuri + 1 ou întreg",
      "40g brânză Pecorino Romano / Parmezan",
      "piper negru proaspăt măcinat",
    ],
    ingredientsEn: [
      "160g wholewheat spaghetti",
      "80g guanciale or lean bacon",
      "2 egg yolks + 1 whole egg",
      "40g Pecorino Romano or Parmesan",
      "freshly ground black pepper",
    ],
    stepsRo: [
      "Fierbe pastele al dente în apă sărată.",
      "Rumește baconul în tigaie fără ulei adăugat.",
      "Bate ouăle cu parmezanul ras și piper.",
      "Amestecă pastele fierbinți cu baconul și crema de ouă (fără foc activ).",
    ],
    stepsEn: [
      "Boil spaghetti al dente in salted water.",
      "Crisp guanciale/bacon in pan without oil.",
      "Whisk eggs with grated cheese and black pepper.",
      "Toss hot pasta with bacon and egg mixture off the heat until creamy.",
    ],
    imageHue: 45,
    imageUrl: "https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "pad-thai-pui",
    nameRo: "Pad Thai thailandez cu pui și arahide",
    nameEn: "Thai chicken Pad Thai with peanuts",
    minutes: 25,
    servings: 2,
    tags: ["pranz", "international", "proteina", "popular"],
    perServing: { kcal: 440, protein: 32, carbs: 54, fat: 12 },
    ingredientsRo: [
      "120g tăieței de orez",
      "250g piept de pui fâșii",
      "1 ou",
      "100g germeni de fasole, ceapă verde",
      "2 linguri sos soia, 1 linguriță paste tamarind, lime, 15g arahide pisate",
    ],
    ingredientsEn: [
      "120g rice noodles",
      "250g sliced chicken breast",
      "1 egg",
      "100g bean sprouts, green onion",
      "2 tbsp soy sauce, tamarind paste, lime, 15g crushed peanuts",
    ],
    stepsRo: [
      "Hidratează tăiețeii de orez în apă caldă.",
      "Sotează puiul în wok cu usturoi, împinge într-o parte și sparge oul.",
      "Adaugă tăiețeii, sosul, germenii de fasole și presară arahide la final.",
    ],
    stepsEn: [
      "Soak rice noodles in warm water.",
      "Stir-fry chicken strips with garlic, push aside and scramble egg.",
      "Add noodles, sauce, bean sprouts and top with lime & peanuts.",
    ],
    imageHue: 35,
    imageUrl: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "chicken-tikka-masala",
    nameRo: "Chicken Tikka Masala cu orez Basmati",
    nameEn: "Indian Chicken Tikka Masala with Basmati rice",
    minutes: 35,
    servings: 3,
    tags: ["pranz", "international", "proteina", "popular"],
    perServing: { kcal: 480, protein: 42, carbs: 38, fat: 18 },
    ingredientsRo: [
      "500g piept de pui în cuburi",
      "150g iaurt grecesc pentru marinadă",
      "400g roșii pasate",
      "1 ceapă, 3 căței usturoi, ghimbir",
      "1 lingură garam masala, turmeric, coriandru, 50ml smântână lichidă",
      "150g orez Basmati",
    ],
    ingredientsEn: [
      "500g diced chicken breast",
      "150g Greek yogurt for marinade",
      "400g tomato passata",
      "1 onion, 3 garlic cloves, ginger",
      "1 tbsp garam masala, turmeric, coriander, 50ml cream",
      "150g Basmati rice",
    ],
    stepsRo: [
      "Marinează puiul în iaurt și condimente 15 min, apoi rumenește-l.",
      "Pregătește sosul din ceapă, usturoi, ghimbir, roșii și condimente.",
      "Incorporează puiul și smântâna, fierbe 15 min. Servește cu orez Basmati.",
    ],
    stepsEn: [
      "Marinate chicken in yogurt & spices 15 mins, then sear.",
      "Make aromatic tomato sauce with onion, garlic, ginger & garam masala.",
      "Simmer chicken in sauce with cream for 15 mins. Serve with rice.",
    ],
    imageHue: 22,
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "caesar-salad-pui",
    nameRo: "Salată Caesar clasică cu pui și crutoane",
    nameEn: "Classic Caesar salad with chicken & croutons",
    minutes: 15,
    servings: 1,
    tags: ["pranz", "international", "proteina", "rapid"],
    perServing: { kcal: 370, protein: 35, carbs: 16, fat: 18 },
    ingredientsRo: [
      "150g piept de pui la grătar",
      "1 căpățână salată Romaine",
      "20g crutoane integrale",
      "20g parmezan ras",
      "2 linguri sos Caesar light (iaurt, anșoa, lămâie, usturoi)",
    ],
    ingredientsEn: [
      "150g grilled chicken breast",
      "1 Romaine lettuce head",
      "20g wholewheat croutons",
      "20g shaved parmesan",
      "2 tbsp light Caesar dressing (yogurt, anchovy, lemon, garlic)",
    ],
    stepsRo: [
      "Taie salata Romaine și amestecă cu sosul Caesar light.",
      "Așază deasupra fâșiile de pui la grătar și crutoanele.",
      "Presară fulgi de parmezan ras.",
    ],
    stepsEn: [
      "Chop Romaine lettuce and toss with light Caesar dressing.",
      "Top with sliced grilled chicken breast and croutons.",
      "Garnish with shaved parmesan cheese.",
    ],
    imageHue: 90,
    imageUrl: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "burrito-bowl-vita",
    nameRo: "Burrito Bowl mexican cu vită și fasole",
    nameEn: "Mexican beef & black bean Burrito Bowl",
    minutes: 25,
    servings: 2,
    tags: ["pranz", "international", "proteina", "popular"],
    perServing: { kcal: 490, protein: 40, carbs: 52, fat: 14 },
    ingredientsRo: [
      "300g carne tocată de vită slabă",
      "100g orez brun / basmati",
      "150g fasole neagră / roșie fiartă",
      "100g porumb dulce, 1/2 avocado, salsa de roșii",
      "condimente Taco / oregano, chimen",
    ],
    ingredientsEn: [
      "300g lean minced beef",
      "100g brown or basmati rice",
      "150g cooked black beans",
      "100g sweetcorn, 1/2 avocado, tomato salsa",
      "Taco seasoning, oregano, cumin",
    ],
    stepsRo: [
      "Călește carnea de vită cu condimentele Taco.",
      "Asamblează bolul: orez la bază, carne, fasole, porumb și avocado.",
      "Adaugă o lingură de salsa de roșii și lămâie verde.",
    ],
    stepsEn: [
      "Brown minced beef with Taco seasoning.",
      "Assemble bowl: rice base, seasoned beef, black beans, corn & avocado.",
      "Top with fresh tomato salsa and lime juice.",
    ],
    imageHue: 25,
    imageUrl: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "poke-bowl-somon",
    nameRo: "Poke Bowl hawaiian cu somon și edamame",
    nameEn: "Hawaiian Poke Bowl with fresh salmon & edamame",
    minutes: 15,
    servings: 1,
    tags: ["pranz", "international", "proteina", "rapid"],
    perServing: { kcal: 450, protein: 34, carbs: 48, fat: 14 },
    ingredientsRo: [
      "120g somon proaspăt în cuburi",
      "100g orez pentru sushi / basmati",
      "50g boabe edamame",
      "1/3 avocado feliat, castravete",
      "1 lingură sos soia, 1 linguriță ulei de susan, semințe de susan",
    ],
    ingredientsEn: [
      "120g fresh raw salmon cubes",
      "100g cooked sushi or basmati rice",
      "50g edamame beans",
      "1/3 sliced avocado, cucumber slices",
      "1 tbsp soy sauce, 1 tsp sesame oil, sesame seeds",
    ],
    stepsRo: [
      "Marinează cuburile de somon în sos soia și ulei de susan 5 min.",
      "Așază orezul la baza bolului.",
      "Ornează cu somonul marinat, edamame, castravete și avocado.",
    ],
    stepsEn: [
      "Marinate salmon cubes in soy sauce and sesame oil 5 mins.",
      "Place warm cooked rice at the base of bowl.",
      "Arrange salmon, edamame, cucumber and avocado neatly.",
    ],
    imageHue: 190,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "risotto-ciuperci",
    nameRo: "Risotto italian cremos cu ciuperci și parmezan",
    nameEn: "Creamy Italian mushroom & parmesan risotto",
    minutes: 30,
    servings: 2,
    tags: ["pranz", "international", "popular", "vegetarian"],
    season: ["ciuperci"],
    perServing: { kcal: 380, protein: 12, carbs: 56, fat: 12 },
    ingredientsRo: [
      "140g orez Arborio",
      "300g ciuperci champignon / hribi",
      "1 ceapă, 2 căței usturoi",
      "500ml supă fierbinte de legume",
      "30g parmezan ras, 1 lingură unt",
    ],
    ingredientsEn: [
      "140g Arborio rice",
      "300g mushrooms (champignon/porcini)",
      "1 onion, 2 garlic cloves",
      "500ml hot vegetable stock",
      "30g grated parmesan, 1 tbsp butter",
    ],
    stepsRo: [
      "Călește ceapa și orezul Arborio în unt 2 minute.",
      "Toarnă supa fierbinte treptat, amestecând continuu timp de 18 min.",
      "Adaugă ciupercile sotate și parmezanul ras la final pentru cremozitate.",
    ],
    stepsEn: [
      "Toast onion and Arborio rice in butter for 2 mins.",
      "Ladle hot stock gradually while stirring for 18 mins.",
      "Fold in sautéed mushrooms and parmesan until rich & creamy.",
    ],
    imageHue: 40,
    imageUrl: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "ramen-porc-ou",
    nameRo: "Ramen japonez cu porc și ou marinat",
    nameEn: "Japanese ramen with pork & soft-boiled egg",
    minutes: 35,
    servings: 2,
    tags: ["pranz", "international", "popular", "proteina"],
    perServing: { kcal: 470, protein: 32, carbs: 48, fat: 18 },
    ingredientsRo: [
      "150g tăieței ramen",
      "200g mușchiuleț de porc rumenit",
      "2 ouă cu gălbenuș moale",
      "600ml supă concentrată de pui/porc cu sos soia și ghimbir",
      "ceapă verde, ciuperci shiitake, alge nori",
    ],
    ingredientsEn: [
      "150g ramen noodles",
      "200g seared pork tenderloin",
      "2 soft-boiled eggs",
      "600ml rich chicken/pork broth with soy & ginger",
      "green onion, shiitake mushrooms, nori seaweed",
    ],
    stepsRo: [
      "Fierbe supa aromată cu soia, ghimbir și usturoi.",
      "Gătește tăiețeii ramen al dente.",
      "Toarnă supa peste tăieței în boluri adânci și decorează cu felii de porc și jumătăți de ou moale.",
    ],
    stepsEn: [
      "Simmer rich broth infused with soy, ginger, and garlic.",
      "Cook ramen noodles al dente.",
      "Ladle broth over noodles, top with sliced pork and halved soft eggs.",
    ],
    imageHue: 15,
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80",
  },

  // ==========================================
  // CINĂ (15 REȚETE)
  // ==========================================
  {
    id: "sarmale-light",
    nameRo: "Sarmale tradiționale light (curcan)",
    nameEn: "Light traditional cabbage rolls (turkey)",
    minutes: 90,
    servings: 6,
    tags: ["traditional", "sarbatori", "proteina", "cina"],
    season: ["varza"],
    perServing: { kcal: 290, protein: 24, carbs: 18, fat: 12 },
    ingredientsRo: [
      "600g carne tocată de curcan",
      "1 varză murată mare",
      "80g orez dintr-o bobitță",
      "2 cepe medii, 2 linguri pastă de roșii",
      "cimbru uscat, mărar, piper",
    ],
    ingredientsEn: [
      "600g minced turkey meat",
      "1 large pickled cabbage",
      "80g white rice",
      "2 medium onions, 2 tbsp tomato paste",
      "dried thyme, dill, black pepper",
    ],
    stepsRo: [
      "Călește ușor ceapa și amestecă cu carnea și orezul.",
      "Desfă frunzele de varză și împăturește sarmalele simetric.",
      "Așază-le în oală cu cimbru și pastă de roșii, fierbe 80-90 min.",
    ],
    stepsEn: [
      "Lightly sauté onion and combine with minced turkey and rice.",
      "Roll meat mixture inside sauerkraut leaves.",
      "Layer in pot with thyme and tomato sauce, simmer 80-90 minutes.",
    ],
    imageHue: 15,
    imageUrl: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "pastrav-cuptor",
    nameRo: "Păstrăv la cuptor cu mămăligă și mujdei",
    nameEn: "Baked trout with polenta and garlic mujdei",
    minutes: 25,
    servings: 2,
    tags: ["cina", "proteina", "light", "popular", "traditional"],
    perServing: { kcal: 360, protein: 38, carbs: 26, fat: 11 },
    ingredientsRo: [
      "2 păstrăvi întregi (aprox. 500g)",
      "1 lămâie, cimbru, rozmarin",
      "100g mălai pentru mămăligă",
      "4 căței usturoi pentru mujdei",
    ],
    ingredientsEn: [
      "2 whole trouts (~500g)",
      "1 lemon, thyme, rosemary",
      "100g cornmeal for polenta",
      "4 garlic cloves for mujdei sauce",
    ],
    stepsRo: [
      "Condimentează păstrăvul cu lămâie și verdețuri, coace 20 min la 200°C.",
      "Prepara mămăliga moale și mujdeiul frecat cu puțină apă și sare.",
      "Servește pe farfurie fierbinte.",
    ],
    stepsEn: [
      "Season trout with lemon and herbs, bake 20 mins at 200°C.",
      "Prepare smooth polenta and garlic mujdei sauce.",
      "Serve hot together.",
    ],
    imageHue: 200,
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "tocanita-ciuperci",
    nameRo: "Tocăniță de ciuperci cu mămăliguță",
    nameEn: "Mushroom stew with creamy polenta",
    minutes: 30,
    servings: 3,
    tags: ["post", "ieftin", "cina", "vegetarian", "traditional"],
    season: ["ciuperci"],
    perServing: { kcal: 280, protein: 10, carbs: 42, fat: 8 },
    ingredientsRo: [
      "500g ciuperci champignon / hribi",
      "2 cepe, 4 căței usturoi",
      "200ml bulion de roșii",
      "1 lingură ulei, mărar proaspăt",
      "120g mălai",
    ],
    ingredientsEn: [
      "500g button mushrooms or porcini",
      "2 onions, 4 garlic cloves",
      "200ml tomato passata",
      "1 tbsp oil, fresh dill",
      "120g cornmeal",
    ],
    stepsRo: [
      "Călește ceapa și ciupercile felii până scade apă.",
      "Adaugă usturoiul, bulionul și fierbe 15 min.",
      "Servește cu mămăligă caldă presărată cu mărar.",
    ],
    stepsEn: [
      "Sauté onions and sliced mushrooms until moisture evaporates.",
      "Add garlic and tomato passata, simmer 15 mins.",
      "Serve over warm polenta garnished with dill.",
    ],
    imageHue: 80,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "dovlecei-umpluti",
    nameRo: "Dovlecei umpluți cu carne de curcan",
    nameEn: "Stuffed zucchini with minced turkey",
    minutes: 45,
    servings: 4,
    tags: ["cina", "proteina", "light", "traditional"],
    season: ["dovlecei"],
    perServing: { kcal: 290, protein: 26, carbs: 16, fat: 13 },
    ingredientsRo: [
      "4 dovlecei medii scobiți",
      "400g carne tocată de curcan",
      "1 ceapă, 50g orez",
      "300ml bulion de roșii, mărar",
    ],
    ingredientsEn: [
      "4 hollowed medium zucchinis",
      "400g minced turkey meat",
      "1 onion, 50g rice",
      "300ml tomato sauce, dill",
    ],
    stepsRo: [
      "Umple dovleceii cu amestecul de carne, ceapă și orez.",
      "Așază-i în tavă adâncă și toarnă bulionul de roșii.",
      "Coace la cuptor 40 min la 190°C.",
    ],
    stepsEn: [
      "Stuff zucchinis with turkey, onion and rice mix.",
      "Arrange in baking dish, add tomato sauce.",
      "Bake for 40 mins at 190°C.",
    ],
    imageHue: 120,
    imageUrl: "https://images.unsplash.com/photo-1592417817098-8f3d6eb19657?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "bulz-ardelenesc",
    nameRo: "Bulz ardelenesc copt la cuptor",
    nameEn: "Baked Transylvanian polenta bulz",
    minutes: 30,
    servings: 2,
    tags: ["traditional", "popular", "cina"],
    perServing: { kcal: 410, protein: 20, carbs: 36, fat: 22 },
    ingredientsRo: [
      "150g mălai pentru mămăligă pripită",
      "80g telemea de oaie sau burduf",
      "2 ouă ochiuri / fierte",
      "1 lingură unt",
    ],
    ingredientsEn: [
      "150g cornmeal for thick polenta",
      "80g sheep burduf or telemea cheese",
      "2 eggs",
      "1 tbsp butter",
    ],
    stepsRo: [
      "Prepara o mămăligă teapănă și formează două bile mari.",
      "Umple mijlocul cu brânză de burduf și unt.",
      "Coace la cuptor 15 min și servește cu ou ochi deasupra.",
    ],
    stepsEn: [
      "Make thick polenta and shape into two balls.",
      "Stuff centers with rich sheep cheese and butter.",
      "Bake 15 mins and crown with a fried egg.",
    ],
    imageHue: 30,
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "somon-lamaie-sparanghel",
    nameRo: "Somon copt la cuptor cu lămâie și sparanghel",
    nameEn: "Baked salmon with lemon & fresh asparagus",
    minutes: 20,
    servings: 2,
    tags: ["cina", "international", "proteina", "light", "rapid"],
    perServing: { kcal: 390, protein: 36, carbs: 8, fat: 24 },
    ingredientsRo: [
      "300g filet de somon proaspăt",
      "200g sparanghel verde",
      "1 lămâie feliată",
      "1 lingură ulei de măsline, usturoi măcinat, mărar",
    ],
    ingredientsEn: [
      "300g fresh salmon fillets",
      "200g fresh green asparagus",
      "1 sliced lemon",
      "1 tbsp olive oil, minced garlic, dill",
    ],
    stepsRo: [
      "Așază fileurile de somon și sparanghelul în tava tapetată cu hârtie.",
      "Stropește cu ulei de măsline, usturoi și felii de lămâie.",
      "Coace 15-18 min la 200°C.",
    ],
    stepsEn: [
      "Place salmon fillets and asparagus on baking tray.",
      "Drizzle olive oil, minced garlic and top with lemon slices.",
      "Bake 15-18 mins at 200°C.",
    ],
    imageHue: 15,
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "tacos-pui-avocado",
    nameRo: "Tacos mexicane cu pui condimentat și salsa",
    nameEn: "Mexican chicken tacos with fresh salsa",
    minutes: 20,
    servings: 2,
    tags: ["cina", "international", "proteina", "popular"],
    perServing: { kcal: 380, protein: 30, carbs: 34, fat: 14 },
    ingredientsRo: [
      "4 foi mici de tortilla din porumb/grâu",
      "250g piept de pui fâșii",
      "1/2 avocado, salată verde, lime",
      "salsa proaspătă de roșii și coriandru",
    ],
    ingredientsEn: [
      "4 small corn/flour tortillas",
      "250g sliced chicken breast",
      "1/2 avocado, lettuce, lime",
      "fresh tomato cilantro salsa",
    ],
    stepsRo: [
      "Sotează puiul cu condimente mexicane (boia, chimen, usturoi).",
      "Încălzește foile de tortilla.",
      "Umple cu pui, salată, felii de avocado și linguri de salsa proaspătă.",
    ],
    stepsEn: [
      "Stir-fry chicken strips with Mexican spices (paprika, cumin, garlic).",
      "Warm tortillas in skillet.",
      "Fill with seasoned chicken, lettuce, avocado slices and fresh salsa.",
    ],
    imageHue: 28,
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "curry-naut-spanac",
    nameRo: "Curry indian de năut cu spanac și lapte de cocos",
    nameEn: "Indian chickpea & spinach coconut curry",
    minutes: 25,
    servings: 3,
    tags: ["cina", "international", "post", "vegetarian", "popular"],
    perServing: { kcal: 340, protein: 14, carbs: 46, fat: 12 },
    ingredientsRo: [
      "400g năut fiert",
      "150g spanac proaspăt",
      "200ml lapte de cocos de gătit",
      "400g roșii pasate",
      "1 ceapă, 2 căței usturoi, 1 lingură pudră curry, ghimbir",
    ],
    ingredientsEn: [
      "400g cooked chickpeas",
      "150g fresh spinach",
      "200ml coconut cooking milk",
      "400g passata tomatoes",
      "1 onion, 2 garlic cloves, 1 tbsp curry powder, ginger",
    ],
    stepsRo: [
      "Călește ceapa, usturoiul și ghimbirul cu pudra de curry.",
      "Adaugă roșiile pasate, năutul și laptele de cocos. Fierbe 15 min.",
      "Incorporează spanacul proaspăt în ultimele 2 minute până se înmoaie.",
    ],
    stepsEn: [
      "Sauté onion, garlic, and ginger with aromatic curry powder.",
      "Pour passata, chickpeas, and coconut milk. Simmer 15 mins.",
      "Stir in fresh spinach during the last 2 mins until wilted.",
    ],
    imageHue: 40,
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "pasta-bolognese-curcan",
    nameRo: "Paste Penne Bolognese cu curcan slab",
    nameEn: "Penne Bolognese with lean turkey mince",
    minutes: 30,
    servings: 3,
    tags: ["cina", "international", "proteina", "popular"],
    perServing: { kcal: 430, protein: 34, carbs: 54, fat: 10 },
    ingredientsRo: [
      "200g paste Penne integrale",
      "350g carne tocată de curcan",
      "400g roșii pasate",
      "1 ceapă, 1 morcov, 2 căței usturoi",
      "busuioc, oregano, 20g parmezan ras",
    ],
    ingredientsEn: [
      "200g wholewheat penne pasta",
      "350g minced turkey meat",
      "400g tomato passata",
      "1 onion, 1 carrot, 2 garlic cloves",
      "basil, oregano, 20g grated parmesan",
    ],
    stepsRo: [
      "Rumenește carnea de curcan cu legumele tocate măunt.",
      "Toarnă sosul de roșii și ierburile aromatice, fierbe 20 min.",
      "Amestecă cu pennele fierte al dente și presară parmezan.",
    ],
    stepsEn: [
      "Brown minced turkey with finely chopped onion & carrot.",
      "Pour tomato passata and herbs, simmer 20 mins into rich ragù.",
      "Toss with al dente penne and top with parmesan.",
    ],
    imageHue: 15,
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3def6164286?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "salata-greceasca-branza",
    nameRo: "Salată grecească autentică cu Feta",
    nameEn: "Authentic Greek salad with Feta cheese",
    minutes: 10,
    servings: 2,
    tags: ["cina", "international", "light", "rapid"],
    perServing: { kcal: 320, protein: 12, carbs: 14, fat: 24 },
    ingredientsRo: [
      "100g brânză Feta autentică",
      "2 roșii mari, 1 castravete",
      "1 ardei gras, 1/2 ceapă roșie",
      "50g măsline Kalamata",
      "2 linguri ulei de măsline extravirgin, oregano",
    ],
    ingredientsEn: [
      "100g authentic Feta cheese block",
      "2 large tomatoes, 1 cucumber",
      "1 green pepper, 1/2 red onion",
      "50g Kalamata olives",
      "2 tbsp extra virgin olive oil, oregano",
    ],
    stepsRo: [
      "Taie roșiile, castraveții și ardeiul în bucăți mari.",
      "Așază deasupra felia de Feta și măslinele Kalamata.",
      "Stropește generos cu ulei de măsline și presară oregano.",
    ],
    stepsEn: [
      "Chop tomatoes, cucumber and peppers into chunky bites.",
      "Crown with whole Feta slab and Kalamata olives.",
      "Drizzle extra virgin olive oil and dried oregano.",
    ],
    imageHue: 100,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "biftec-vita-broccoli",
    nameRo: "Stir-fry chinezesc de vită cu broccoli",
    nameEn: "Chinese beef & broccoli stir-fry",
    minutes: 20,
    servings: 2,
    tags: ["cina", "international", "proteina", "rapid"],
    perServing: { kcal: 370, protein: 40, carbs: 14, fat: 16 },
    ingredientsRo: [
      "350g vrăbioară / mușchi de vită fâșii",
      "250g buchețele de broccoli proaspăt",
      "2 căței usturoi, ghimbir ras",
      "2 linguri sos soia, 1 linguriță ulei susan, susan alb",
    ],
    ingredientsEn: [
      "350g beef sirloin strips",
      "250g fresh broccoli florets",
      "2 garlic cloves, grated ginger",
      "2 tbsp soy sauce, 1 tsp sesame oil, white sesame",
    ],
    stepsRo: [
      "Sotează vătămător fâșiile de vită la foc iute 3-4 min în wok.",
      "Opărește scurt broccoli-ul și adaugă-l în wok cu sosul soia și ghimbirul.",
      "Presară semințe de susan și servește fierbinte.",
    ],
    stepsEn: [
      "Sear beef strips over high heat in wok for 3-4 mins.",
      "Blanch broccoli florets and toss into wok with soy sauce & ginger.",
      "Sprinkle sesame seeds and serve piping hot.",
    ],
    imageHue: 120,
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "pui-teriyaki-susan",
    nameRo: "Pui Teriyaki cu susan și orez iasomie",
    nameEn: "Chicken Teriyaki with sesame & jasmine rice",
    minutes: 20,
    servings: 2,
    tags: ["cina", "international", "proteina", "popular"],
    perServing: { kcal: 440, protein: 36, carbs: 50, fat: 10 },
    ingredientsRo: [
      "350g piept de pui cuburi",
      "100g orez iasomie",
      "3 linguri sos Teriyaki light",
      "ceapă verde, semințe de susan",
    ],
    ingredientsEn: [
      "350g diced chicken breast",
      "100g jasmine rice",
      "3 tbsp light Teriyaki sauce",
      "green onion, sesame seeds",
    ],
    stepsRo: [
      "Frige puiul în tigaie până se rumenește.",
      "Toarnă sosul Teriyaki și glasează carnea 3-4 min la foc mic.",
      "Servește peste orez iasomie aburind și presară ceapă verde.",
    ],
    stepsEn: [
      "Sear chicken cubes until golden.",
      "Pour Teriyaki sauce and glaze chicken for 3-4 mins on low heat.",
      "Serve over steaming jasmine rice and top with green onions.",
    ],
    imageHue: 30,
    imageUrl: "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "musaca-greceasca-light",
    nameRo: "Musaca grecească light cu vinete și vită",
    nameEn: "Light Greek Moussaka with eggplant & beef",
    minutes: 50,
    servings: 4,
    tags: ["cina", "international", "proteina", "popular"],
    season: ["vinete"],
    perServing: { kcal: 380, protein: 28, carbs: 26, fat: 18 },
    ingredientsRo: [
      "2 vinete mari coapte pe tigaia grill",
      "400g carne tocată de vită slabă",
      "400g roșii pasate, 1 ceapă, scorțișoară",
      "200g iaurt grecesc 2% amestecat cu 1 ou pentru stratul superior",
    ],
    ingredientsEn: [
      "2 large grilled eggplant slices",
      "400g lean minced beef",
      "400g tomato passata, 1 onion, pinch of cinnamon",
      "200g Greek yogurt 2% whisked with 1 egg for topping",
    ],
    stepsRo: [
      "Frige feliile de vinete fără ulei pe grill.",
      "Pregătește sosul de vită cu roșii și un praf de scorțișoară.",
      "Așază straturi alternante de vinete și carne, toarnă crema de iaurt deasupra și coace 35 min.",
    ],
    stepsEn: [
      "Grill eggplant slices without added oil.",
      "Simmer minced beef sauce with tomatoes and pinch of cinnamon.",
      "Layer eggplants and beef, top with yogurt-egg mix and bake 35 mins.",
    ],
    imageHue: 15,
    imageUrl: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "quiche-lorraine-light",
    nameRo: "Quiche francez cu șuncă și praz",
    nameEn: "French leek & ham Quiche (Light)",
    minutes: 40,
    servings: 4,
    tags: ["cina", "international"],
    perServing: { kcal: 360, protein: 18, carbs: 28, fat: 20 },
    ingredientsRo: [
      "1 foaie aluat fraged sau foietaj light",
      "150g șuncă de curcan / de praga",
      "1 fir praz mare feliat",
      "3 ouă, 150ml lapte, 40g emmental / cascaval ras",
    ],
    ingredientsEn: [
      "1 light pastry sheet",
      "150g turkey or Prague ham diced",
      "1 large sliced leek",
      "3 eggs, 150ml milk, 40g shredded cheese",
    ],
    stepsRo: [
      "Călește prazul feliat până se înmoaie.",
      "Bate ouăle cu laptele, brânza rasă și șunca.",
      "Toarnă în tava tapetată cu aluat și coace 30 min la 190°C.",
    ],
    stepsEn: [
      "Sauté sliced leeks until soft.",
      "Whisk eggs with milk, cheese, and diced ham.",
      "Pour into pastry-lined pie dish and bake 30 mins at 190°C.",
    ],
    imageHue: 42,
    imageUrl: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: "falafel-lipie-hummus",
    nameRo: "Wrap oriental cu falafel, hummus și salată",
    nameEn: "Middle Eastern Falafel wrap with hummus",
    minutes: 15,
    servings: 1,
    tags: ["cina", "international", "post", "vegetarian", "rapid"],
    perServing: { kcal: 410, protein: 16, carbs: 56, fat: 14 },
    ingredientsRo: [
      "1 lipie libaneză integrală",
      "4 chifteluțe falafel copt",
      "2 linguri hummus clasic",
      "salată roșii, castravete, sos tahini",
    ],
    ingredientsEn: [
      "1 wholewheat pita / flatbread",
      "4 baked falafel balls",
      "2 tbsp classic hummus",
      "tomato cucumber salad, tahini sauce",
    ],
    stepsRo: [
      "Încălzește lipia libaneză și falafelu-ul copt.",
      "Unge cu hummus, adaugă falafelul zdrobit ușor și salata.",
      "Stropește cu sos tahini și rulează strâns.",
    ],
    stepsEn: [
      "Warm flatbread and baked falafel.",
      "Spread hummus, top with lightly crushed falafel and fresh salad.",
      "Drizzle tahini sauce and wrap tightly.",
    ],
    imageHue: 45,
    imageUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
  },
];

export function recipeName(recipe: Recipe, locale: "ro" | "en") {
  return locale === "ro" ? recipe.nameRo : recipe.nameEn;
}


